//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordisoftware.HebrewCalendar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::Ordisoftware.HebrewCalendar.ControlLocation MainFormPosition {
            get {
                return ((global::Ordisoftware.HebrewCalendar.ControlLocation)(this["MainFormPosition"]));
            }
            set {
                this["MainFormPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormLeft {
            get {
                return ((int)(this["MainFormLeft"]));
            }
            set {
                this["MainFormLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormTop {
            get {
                return ((int)(this["MainFormTop"]));
            }
            set {
                this["MainFormTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormWidth {
            get {
                return ((int)(this["MainFormWidth"]));
            }
            set {
                this["MainFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormHeight {
            get {
                return ((int)(this["MainFormHeight"]));
            }
            set {
                this["MainFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainFormState"]));
            }
            set {
                this["MainFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ESCtoExit {
            get {
                return ((bool)(this["ESCtoExit"]));
            }
            set {
                this["ESCtoExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmClosing {
            get {
                return ((bool)(this["ConfirmClosing"]));
            }
            set {
                this["ConfirmClosing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New")]
        public string FontName {
            get {
                return ((string)(this["FontName"]));
            }
            set {
                this["FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTips {
            get {
                return ((bool)(this["ShowTips"]));
            }
            set {
                this["ShowTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int ShabatDay {
            get {
                return ((int)(this["ShabatDay"]));
            }
            set {
                this["ShabatDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Month")]
        public global::Ordisoftware.HebrewCalendar.ViewModeType CurrentView {
            get {
                return ((global::Ordisoftware.HebrewCalendar.ViewModeType)(this["CurrentView"]));
            }
            set {
                this["CurrentView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSLatitude {
            get {
                return ((string)(this["GPSLatitude"]));
            }
            set {
                this["GPSLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSLongitude {
            get {
                return ((string)(this["GPSLongitude"]));
            }
            set {
                this["GPSLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CountDayMoonAsSun {
            get {
                return ((bool)(this["CountDayMoonAsSun"]));
            }
            set {
                this["CountDayMoonAsSun"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=Hebrew-calendar")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TextColor {
            get {
                return ((global::System.Drawing.Color)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TextBackground {
            get {
                return ((global::System.Drawing.Color)(this["TextBackground"]));
            }
            set {
                this["TextBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LemonChiffon")]
        public global::System.Drawing.Color NavigateTopColor {
            get {
                return ((global::System.Drawing.Color)(this["NavigateTopColor"]));
            }
            set {
                this["NavigateTopColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public global::System.Drawing.Color NavigateMiddleColor {
            get {
                return ((global::System.Drawing.Color)(this["NavigateMiddleColor"]));
            }
            set {
                this["NavigateMiddleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Honeydew")]
        public global::System.Drawing.Color NavigateBottomColor {
            get {
                return ((global::System.Drawing.Color)(this["NavigateBottomColor"]));
            }
            set {
                this["NavigateBottomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MainForm")]
        public global::Ordisoftware.HebrewCalendar.TrayIconClickOpen TrayIconClickOpen {
            get {
                return ((global::Ordisoftware.HebrewCalendar.TrayIconClickOpen)(this["TrayIconClickOpen"]));
            }
            set {
                this["TrayIconClickOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupHide {
            get {
                return ((bool)(this["StartupHide"]));
            }
            set {
                this["StartupHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public decimal ReminderInterval {
            get {
                return ((decimal)(this["ReminderInterval"]));
            }
            set {
                this["ReminderInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReminderEnabled {
            get {
                return ((bool)(this["ReminderEnabled"]));
            }
            set {
                this["ReminderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindNewYearD1 {
            get {
                return ((bool)(this["TorahEventRemindNewYearD1"]));
            }
            set {
                this["TorahEventRemindNewYearD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindNewYearD10 {
            get {
                return ((bool)(this["TorahEventRemindNewYearD10"]));
            }
            set {
                this["TorahEventRemindNewYearD10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindPessahD1 {
            get {
                return ((bool)(this["TorahEventRemindPessahD1"]));
            }
            set {
                this["TorahEventRemindPessahD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindPessahD7 {
            get {
                return ((bool)(this["TorahEventRemindPessahD7"]));
            }
            set {
                this["TorahEventRemindPessahD7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindChavouotDiet {
            get {
                return ((bool)(this["TorahEventRemindChavouotDiet"]));
            }
            set {
                this["TorahEventRemindChavouotDiet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindChavouot1 {
            get {
                return ((bool)(this["TorahEventRemindChavouot1"]));
            }
            set {
                this["TorahEventRemindChavouot1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindChavouot2 {
            get {
                return ((bool)(this["TorahEventRemindChavouot2"]));
            }
            set {
                this["TorahEventRemindChavouot2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindYomTerouah {
            get {
                return ((bool)(this["TorahEventRemindYomTerouah"]));
            }
            set {
                this["TorahEventRemindYomTerouah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindYomHaKipourim {
            get {
                return ((bool)(this["TorahEventRemindYomHaKipourim"]));
            }
            set {
                this["TorahEventRemindYomHaKipourim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindSoukotD1 {
            get {
                return ((bool)(this["TorahEventRemindSoukotD1"]));
            }
            set {
                this["TorahEventRemindSoukotD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindSoukotD8 {
            get {
                return ((bool)(this["TorahEventRemindSoukotD8"]));
            }
            set {
                this["TorahEventRemindSoukotD8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemindShabat {
            get {
                return ((bool)(this["RemindShabat"]));
            }
            set {
                this["RemindShabat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MonthViewSunToolTips {
            get {
                return ((bool)(this["MonthViewSunToolTips"]));
            }
            set {
                this["MonthViewSunToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 0, 0")]
        public global::System.Drawing.Color CurrentDayColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentDayColor"]));
            }
            set {
                this["CurrentDayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color TorahEventColor {
            get {
                return ((global::System.Drawing.Color)(this["TorahEventColor"]));
            }
            set {
                this["TorahEventColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color SeasonEventColor {
            get {
                return ((global::System.Drawing.Color)(this["SeasonEventColor"]));
            }
            set {
                this["SeasonEventColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public global::System.Drawing.Color MoonEventColor {
            get {
                return ((global::System.Drawing.Color)(this["MoonEventColor"]));
            }
            set {
                this["MoonEventColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGoldenrod")]
        public global::System.Drawing.Color FullMoonColor {
            get {
                return ((global::System.Drawing.Color)(this["FullMoonColor"]));
            }
            set {
                this["FullMoonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemindShabatOnlyLight {
            get {
                return ((bool)(this["RemindShabatOnlyLight"]));
            }
            set {
                this["RemindShabatOnlyLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal RemindShabatHoursBefore {
            get {
                return ((decimal)(this["RemindShabatHoursBefore"]));
            }
            set {
                this["RemindShabatHoursBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public decimal RemindShabatEveryMinutes {
            get {
                return ((decimal)(this["RemindShabatEveryMinutes"]));
            }
            set {
                this["RemindShabatEveryMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckUpdateAtStartup {
            get {
                return ((bool)(this["CheckUpdateAtStartup"]));
            }
            set {
                this["CheckUpdateAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public decimal RemindCelebrationHoursBefore {
            get {
                return ((decimal)(this["RemindCelebrationHoursBefore"]));
            }
            set {
                this["RemindCelebrationHoursBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public decimal RemindCelebrationEveryMinutes {
            get {
                return ((decimal)(this["RemindCelebrationEveryMinutes"]));
            }
            set {
                this["RemindCelebrationEveryMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindDayNewYearD1 {
            get {
                return ((bool)(this["TorahEventRemindDayNewYearD1"]));
            }
            set {
                this["TorahEventRemindDayNewYearD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindDayNewYearD10 {
            get {
                return ((bool)(this["TorahEventRemindDayNewYearD10"]));
            }
            set {
                this["TorahEventRemindDayNewYearD10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDayPessahD1 {
            get {
                return ((bool)(this["TorahEventRemindDayPessahD1"]));
            }
            set {
                this["TorahEventRemindDayPessahD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDayPessahD7 {
            get {
                return ((bool)(this["TorahEventRemindDayPessahD7"]));
            }
            set {
                this["TorahEventRemindDayPessahD7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorahEventRemindDayChavouotDiet {
            get {
                return ((bool)(this["TorahEventRemindDayChavouotDiet"]));
            }
            set {
                this["TorahEventRemindDayChavouotDiet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDayChavouot1 {
            get {
                return ((bool)(this["TorahEventRemindDayChavouot1"]));
            }
            set {
                this["TorahEventRemindDayChavouot1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDayChavouot2 {
            get {
                return ((bool)(this["TorahEventRemindDayChavouot2"]));
            }
            set {
                this["TorahEventRemindDayChavouot2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDayYomTerouah {
            get {
                return ((bool)(this["TorahEventRemindDayYomTerouah"]));
            }
            set {
                this["TorahEventRemindDayYomTerouah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDayYomHaKipourim {
            get {
                return ((bool)(this["TorahEventRemindDayYomHaKipourim"]));
            }
            set {
                this["TorahEventRemindDayYomHaKipourim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDaySoukotD1 {
            get {
                return ((bool)(this["TorahEventRemindDaySoukotD1"]));
            }
            set {
                this["TorahEventRemindDaySoukotD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TorahEventRemindDaySoukotD8 {
            get {
                return ((bool)(this["TorahEventRemindDaySoukotD8"]));
            }
            set {
                this["TorahEventRemindDaySoukotD8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSCountry {
            get {
                return ((string)(this["GPSCountry"]));
            }
            set {
                this["GPSCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPSCity {
            get {
                return ((string)(this["GPSCity"]));
            }
            set {
                this["GPSCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BalloonEnabled {
            get {
                return ((bool)(this["BalloonEnabled"]));
            }
            set {
                this["BalloonEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowReminderInTaskBar {
            get {
                return ((bool)(this["ShowReminderInTaskBar"]));
            }
            set {
                this["ShowReminderInTaskBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BalloonAutoHide {
            get {
                return ((bool)(this["BalloonAutoHide"]));
            }
            set {
                this["BalloonAutoHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 230")]
        public global::System.Drawing.Color ReminderCurrentDayColor {
            get {
                return ((global::System.Drawing.Color)(this["ReminderCurrentDayColor"]));
            }
            set {
                this["ReminderCurrentDayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReminderUseColors {
            get {
                return ((bool)(this["ReminderUseColors"]));
            }
            set {
                this["ReminderUseColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GenerateIntervalMin {
            get {
                return ((int)(this["GenerateIntervalMin"]));
            }
            set {
                this["GenerateIntervalMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GenerateIntervalMax {
            get {
                return ((int)(this["GenerateIntervalMax"]));
            }
            set {
                this["GenerateIntervalMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GenerateIntervalDefault {
            get {
                return ((int)(this["GenerateIntervalDefault"]));
            }
            set {
                this["GenerateIntervalDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int GenerateIntervalPeriod {
            get {
                return ((int)(this["GenerateIntervalPeriod"]));
            }
            set {
                this["GenerateIntervalPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("242, 242, 242")]
        public global::System.Drawing.Color ReminderShabatDayColor {
            get {
                return ((global::System.Drawing.Color)(this["ReminderShabatDayColor"]));
            }
            set {
                this["ReminderShabatDayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("245, 255, 240")]
        public global::System.Drawing.Color ReminderDayColor {
            get {
                return ((global::System.Drawing.Color)(this["ReminderDayColor"]));
            }
            set {
                this["ReminderDayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NextCelebrationsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["NextCelebrationsFormLocation"]));
            }
            set {
                this["NextCelebrationsFormLocation"] = value;
            }
        }
    }
}
