Name: {app}\*; Type: files
Name: {app}\Bin\*; Type: filesandordirs
Name: {app}\Documents\*; Type: filesandordirs
Name: {app}\Help\*; Type: filesandordirs
Name: {app}\Project\*; Type: filesandordirs
Name: {app}\Setup\*; Type: filesandordirs
Name: {app}\{cm:LaunchProgram,{#MyAppName}}.*; Type: files
Name: {group}\{cm:LaunchProgram,{#MyAppName}}.*; Type: files
Name: {group}\{#MyAppName}; Type: filesandordirs
